[project]
name = "github-uebung-2-fork"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
